### ISSUE TITLE
not working 

### ISSUE THREAD

**Issue by b1nslashsh** [magiclen/xcompress#4]
./xcompress 
thread 'main' panicked at 'not implemented', src/main.rs:136:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[1]    31014 abort      ./xcompress

@GallagherCommaJack @magiclen 
any idea why this happening

**Comment by b1nslashsh** [comment]
my bad zrgs are always mandatory

**Comment by magiclen** [comment]
The error message has been improved. Thanks.
